version: '3'

services:
  app:
    build: .
    command: wait-for db:3306 -t 40 -- ./entrypoint.sh
    ports:
      - 8000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db
    
  db:
    image: mysql:5.7.16
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=mydb
    volumes:
      - ./dbdata:/var/lib/mysql